### ISSUE TITLE
OpenCL 2.x support

### ISSUE THREAD

**Issue by thewilsonator** [DerelictOrg/DerelictCL#2]
With the progress of dcompute coming along nicely I am now at the point where I can start testing OpenCL. To do so I need derelict-cl to be able to support OpenCL 2.x

If someone could point me in the direction of how to go about supporting 2.x in derelict that would be much appreciated.

**Comment by mdparker** [comment]
I don't know anything about OpenCL, but what I generally do is diff the headers against which the current binding was made with the headers from the new version. Then I add the changes in a new branch and, when I'm satisfied that they are complete, I merge them into master and tag a new release (usually bumping the minor version). Looking at the source, that approach should apply here as well, i.e. it isn't as convoluted as the OpenGL bindings. 

Also, I see the function pointer aliases here are all declared `nothrow` as they should be, but `@nogc` is missing.

**Comment by p0nce** [comment]
I started to look at it but realized I haven't a single OpenCL 2.0 device.
It's all about downloading the official headers which I think have a similar split to derelict-cl.

**Comment by thewilsonator** [comment]
Really? GPUs yes, but my core i5 760 has drivers for 2.1
Thats what I plan to test dcompute against.
I'll diff the 1.2 header against the 2.1 and see what has changed and make a PR sometime soonish.

**Comment by p0nce** [comment]
Well I have only 3/4 years old computers currently.
